# Generated by Django 4.2.1 on 2023-11-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image_list',
            field=models.ImageField(default=0, upload_to='product_category_list'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image_main',
            field=models.ImageField(blank=True, upload_to='prodict_category_main'),
        ),
    ]
