# Generated by Django 4.2.1 on 2023-11-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_remove_productcategory_image_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='image_main',
        ),
    ]
