# Generated by Django 4.2.1 on 2023-11-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_productcategory_image_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='image_list',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default=0, upload_to='category_images'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SpecialProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='special_products_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.productcategory')),
            ],
        ),
    ]
