# Generated by Django 4.2.1 on 2023-11-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_products',
            field=models.ManyToManyField(blank=True, to='Store.specialproducts'),
        ),
    ]
