# Generated by Django 4.2.1 on 2023-12-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_product_special_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='special_products',
        ),
    ]
