# Generated by Django 4.2.1 on 2024-01-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_remove_product_special_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee', models.PositiveIntegerField(default=None)),
                ('thread_diameter', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('material', models.CharField(default=None, max_length=30)),
                ('mounting_method', models.CharField(default=None, max_length=30)),
                ('purpose_mixer', models.CharField(default=None, max_length=50)),
                ('mixer_type', models.CharField(default=None, max_length=50)),
                ('type_liner', models.CharField(default=None, max_length=50)),
                ('width', models.PositiveIntegerField(default=None)),
                ('length', models.PositiveIntegerField(default=None)),
                ('weight', models.PositiveIntegerField(default=None)),
                ('height', models.PositiveIntegerField(default=None)),
                ('wear_resistance', models.CharField(default=None, max_length=20)),
                ('country', models.CharField(default=None, max_length=20)),
                ('basis', models.CharField(default=None, max_length=20)),
                ('color', models.CharField(default=None, max_length=20)),
                ('putty_type', models.CharField(default=None, max_length=20)),
                ('drying_time', models.PositiveIntegerField(default=None)),
                ('volume', models.PositiveIntegerField(default=None)),
                ('thickness', models.PositiveIntegerField(default=None)),
                ('glass_package', models.CharField(default=None, max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.product')),
            ],
        ),
    ]
