# Generated by Django 5.0.1 on 2024-07-10 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
