# Generated by Django 5.0.1 on 2024-07-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_alter_characteristics_basis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='drying_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время высыхания'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='guarantee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='thickness',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Толщина'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объём'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
