# Generated by Django 5.0.1 on 2024-07-09 09:43

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Store', '0012_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой')], max_length=20)),
                ('status', models.CharField(choices=[('accept', 'Принят'), ('collect', 'В сборке'), ('on_the_way', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='accept', max_length=10)),
                ('delivery_method', models.CharField(choices=[('courier', 'Курьер (Доставка курьером)'), ('pickup', 'Самовывоз (На пункте выдачи)')], max_length=20)),
                ('address', models.TextField(max_length=250)),
                ('comment', models.TextField(blank=True, max_length=250)),
                ('recipient', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.product')),
            ],
        ),
    ]
